version: '3.1'
services:

  build:
    container_name: GeprisBuildingService
    build:
      context: .
      dockerfile: ./src/scripts/Dockerfile
    volumes:
      - ./src/scripts/models:/models
      - ./data:/gepris_data
